DROP TABLE IF EXISTS CP_Account;
DROP TABLE IF EXISTS CP_Device;
DROP TABLE IF EXISTS CP_Device_Model;
DROP TABLE IF EXISTS CP_Email_Final;
DROP TABLE IF EXISTS Link;
DROP TABLE IF EXISTS EmailEvent;
DROP TABLE IF EXISTS EmailSentTo;
DROP TABLE IF EXISTS EmailAddress;
DROP TABLE IF EXISTS Domain;
DROP TABLE IF EXISTS Email;
DROP TABLE IF EXISTS EmailCampaign;
DROP TABLE IF EXISTS Audience;
DROP TABLE IF EXISTS SubjectLine;
DROP TABLE IF EXISTS State;
DROP TABLE IF EXISTS Zip;
DROP TABLE IF EXISTS Language;
DROP TABLE IF EXISTS IncomeLevel;
DROP TABLE IF EXISTS Gender;
DROP TABLE IF EXISTS DeviceRegistration;
DROP TABLE IF EXISTS CustomerAccount;
DROP TABLE IF EXISTS RegistrationSource;
DROP TABLE IF EXISTS Purchase;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Device;
DROP TABLE IF EXISTS Device_Type;
DROP TABLE IF EXISTS Carrier;



CREATE TABLE cpe366.CP_Account LIKE cpe366_readonly.CP_Account;
INSERT cpe366.CP_Account SELECT * FROM cpe366_readonly.CP_Account;

CREATE TABLE cpe366.CP_Device LIKE cpe366_readonly.CP_Device;
INSERT cpe366.CP_Device SELECT * FROM cpe366_readonly.CP_Device;

CREATE TABLE cpe366.CP_Device_Model LIKE cpe366_readonly.CP_Device_Model;
INSERT cpe366.CP_Device_Model SELECT * FROM cpe366_readonly.CP_Device_Model;

CREATE TABLE cpe366.CP_Email_Final LIKE cpe366_readonly.CP_Email_Final;
INSERT cpe366.CP_Email_Final SELECT * FROM cpe366_readonly.CP_Email_Final;
